### ISSUE TITLE
no ical access

### ISSUE THREAD

**Issue by badkey** [kiwanami/emacs-calfw#119]
Accessing an ical calendar does not work (not for public nor for private calendars). The calendar in emacs showing up is empty, e.g.
 : (cfw:open-ical-calendar "https://calendar.google.com/calendar/ical/de.christian%23holiday%40group.v.calendar.google.com/public/basic.ics")
Any suggestions?

**Comment by cdeleuze** [comment]
It does work for me.  Can you access this URL from emacs (eg with M-x eww) ? from a browser ? Could be a problem with a proxy...

**Comment by badkey** [comment]
As a matter of fact, it does work again... thank you anyway.
