### ISSUE TITLE
calfw2org

### ISSUE THREAD

**Issue by dsteuer** [kiwanami/emacs-calfw#39]
Hi!
I´m not happy with calfw introducing a template in my list of templates in org.
Furthermore, when I tried it, it just throw some error. What is it supposed to do?

This is the way emacs reacts upon C-c c c.
---
* 
 %![Error: (error Not found cfw:component attribute...)]
---

How to disable this template in my template list? And the "c" is hardcoded, so 
any "c" template would be overridden?

emacs 24.3.1, org and calfw from git.

**Comment by myuhe** [comment]
If `cfw:org-capture-template` is `nil`, you can disable this template.

``` lisp
(setq cfw:org-capture-template nil)
```

**Comment by dsteuer** [comment]
Thx for the hint and thx for working on calfw again!
Detlef
