### ISSUE TITLE
Any new release ?

### ISSUE THREAD

**Issue by nlamirault** [kiwanami/emacs-calfw#48]
The last date of release dated October 10 , 2011. Is there a new version planned?

**Comment by kiwanami** [comment]
Yes. Just I have little time to release work...
The current version had included big patch 4ee6d371011c1a311ea7af1ea410d28d02e5cff1.
I would update readme and make a next release v1.4 soon.
Thank you for your comment!

**Comment by nlamirault** [comment]
Great !

Masashi Sakurai <notifications@github.com> writes:

> Yes. Just I have little time to release work...
> The current version had included big patch 4ee6d37.
> I would update readme and make a next release v1.4 soon.
> Thank you for your comment!
>
> —
> Reply to this email directly or view it on GitHub.
>
>


-- 
Nicolas Lamirault

**Comment by jwiegley** [comment]
@kiwanami This project is simply amazing!!  I was wanting a graphical, iCal-like calendar in Emacs just yesterday, and then by change stumbled upon this.  It's perfect!

**Comment by kiwanami** [comment]
@jwiegley Thank you for your comment! I'm glad to know you like this.

I have little time to face the calfw project now. I'll take some time to work on calfw next week.

**Comment by nlamirault** [comment]
Thanks for the 1.4 version
