### ISSUE TITLE
ICS recurrent event

### ISSUE THREAD

**Issue by nlamirault** [kiwanami/emacs-calfw#49]
hi
i've setup calfw to display some ics calendars from my Google account. It works fine, but i've got an error: reccurent event aren't display (like weekly or yearly event).
Any idea ?

**Comment by cdeleuze** [comment]
ical recurrent events are not supported (yet) as indicated in function cfw:ical-events-get-dates in calfw-ical.el.  Maybe this limitation should be stated in the readme.md (in the ical section).

A workaround could be to convert your ical file to diary.  According to emacs's calendar/icalendar.el it seems it knows how to convert ical recurring events to diary cyclic entries.  I never tried this, though, and  a 'FIXME FIXME' tag in icalendar--convert-recurring-to-diary calls for looking this up in details.

I have a few cyclic entries in my diary and calfw handles them correctly.

**Comment by kiwanami** [comment]
Hi, @nlamirault @cdeleuze 
I'm sorry for the lack of reccurent event implementation.
I also received similar issue at #8.
Hmm, because I hardly use ics files now, it would be difficult to take a time to fix this...

**Comment by kiwanami** [comment]
Now I'm trying to implement recurrent event functions.
I'll update the status at #8. So, I close this issue.

**Comment by nlamirault** [comment]
Thanks
