### ISSUE TITLE
Highlight important entries

### ISSUE THREAD

**Issue by Mahadras** [kiwanami/emacs-calfw#58]
Hi,

I've been starting to use calfw because I think it's awesome. However, with one issue I got no where. I'm using diary mode and want to highlight important diary entries. As far as I know the readme gives no information about that (except I've overseen something). Is it even a feature or would I have to use second source to highlight some entries with another color.

Many Thanks in advance

**Comment by kiwanami** [comment]
Hi @Mahadras 
Thank you for your message.

calfw.el don't have a function to highlight some entries. Some adapter codes do that, such as calfw-org.el.  So if the highlighting function is commonly needed for diary users, I think it should be implemented at calfw-diary.el.

Well, because I don't usually use diary mode, I don't have any idea how do we highlight some diary entries. Please let me see the sample diary source and expected image, and we would discuss how do we that.

**Comment by Mahadras** [comment]
Hey, thanks for that fast answer.

Diary source: http://image-upload.de/file/KjeSNz/95307ea694.jpg
Expected: http://image-upload.de/file/EEUKBw/6d6fe3b916.jpg (I had to photoshop it so it looks very different)

I hope you kind off get the idea :).

So the think is it doens't matter how the entry is highlited (e.g bold, different color, underline, etc.). What matters is that you can create an entry that stick out.

In the readme I've seen a screenshot where 2 sources are in one calendar buffer. https://camo.githubusercontent.com/bcf0ca5fd834e2ea161099edfcb8bc969edebbc1/68747470733a2f2f6361636f6f2e636f6d2f6469616772616d732f4f6e6a4b6742486174306b48733078702d39453545302e706e673f77696474683d363030

Now, can you edit 2 calendar sources in one buffer? I've tried to add multiple sources to one buffer but sadly failed.
That would be enough if I can add entries in two different sources in one buffer.

Thanks for helping!

**Comment by kiwanami** [comment]
I'm sorry for my late response.
Thank you for your idea and info.

Yes, calfw can merge multiple diary sources into one buffer, like following:

```el
(let* ((source1 (cfw:cal-create-source)) ;; default diary file "~/diary"
         (source2   (make-cfw:source
                     :name "calendar diary"
                     :color "White" ;; foreground color
                     :opt-face '(:background "#e04030") ;; background color
                     :data (lambda (begin end)
                             (let ((diary-file "~/diary2")) ;; important diary file
                               (cfw:cal-schedule-period-to-calendar begin end)))))
         (cp (cfw:create-calendar-component-buffer
              :view 'month
              :custom-map cfw:cal-schedule-map
              :contents-sources (list source1 source2))))
  (switch-to-buffer (cfw:cp-get-buffer cp)))
```
Here, this code assumes the important diary file is located at `~/diary2`.
Can this help you?

**Comment by Mahadras** [comment]
Thanks for this awesome code!
But I'm a bit confused because I'm still a emacs/cfw beginner. I can say that the code is exactly what I need (thanks for that!!). However, I'm struggling with the usability. The code is in my .emacs file and also there is ~/diary and ~/diary2. 
When I start emacs the sources and the component buffer which contains the two sources should be created.
Do I still need to go like: cfw:open-diary-calendar like I always did? Because the diary mode only shows one calendar (calendar diary in brown, ~/diary).
What did I forget? :)

**Comment by kiwanami** [comment]
Ok. How about this?
I just make it interactive command. Placing this code at your .emacs or init.el, you can open the calendar buffer with `M-x cfw:open-diary-calendar2`.

```el
(defun cfw:open-diary-calendar2 ()
  (interactive)
  (let* ((source1 (cfw:cal-create-source)) ;; default diary file "~/diary"
         (source2   (make-cfw:source
                     :name "calendar diary"
                     :color "White" ;; foreground color
                     :opt-face '(:background "#e04030") ;; background color
                     :data (lambda (begin end)
                             (let ((diary-file "~/diary2")) ;; important diary file
                               (cfw:cal-schedule-period-to-calendar begin end)))))
         (cp (cfw:create-calendar-component-buffer
              :view 'month
              :custom-map cfw:cal-schedule-map
              :contents-sources (list source1 source2))))
    (switch-to-buffer (cfw:cp-get-buffer cp))))
```

**Comment by Mahadras** [comment]
This works perfectly. I can work with this now. Thank you very much.

**Comment by kiwanami** [comment]
That's good! Thank you.
