### ISSUE TITLE
Default Org Color

### ISSUE THREAD

**Issue by mankoff** [kiwanami/emacs-calfw#70]
Sorry to post trivial issues here, but I'm having trouble figuring out how to set this based on the documentation.

How can I set the default color of Org items? Currently they are `Seagreen4`. I'd prefer them to be white.

**Comment by skyer9** [comment]
currently you can overwrite this function

(defun cfw:org-create-source (&optional color)
  "Create org-agenda source."
  (make-cfw:source
   :name "org-agenda"
   :color (or color "Seagreen4")
   :data 'cfw:org-schedule-period-to-calendar))

i will fix it this in this weekend.
i can make time in weekend only.

**Comment by kiwanami** [comment]
Hi, @mankoff @skyer9 
I also think the default color should be extracted as a customize variable.
Please follow #73.

**Comment by mankoff** [comment]
Seems like this issue is covered in #73
