### ISSUE TITLE
No clickable link generated for org items with date-only timestamps

### ISSUE THREAD

**Issue by joonro** [kiwanami/emacs-calfw#80]
Hi,

I just started using it - thanks for the great package. 

It seems `calfw-org` does not generate clickable links (for `cfw:org-onclick`) for org items with date-only timestamps.

For example, an item with timestamp `<2016-03-01 Tue 09:30>` is shown in the calender with clickable 09:30 link, but another item with timestamp `<2016-03-01 Tue>` is shown in the calender without any clickable links. (`<RET>` does not work either). 

Please let me know if I'm doing something wrong. Thank you so much.

**Comment by kiwanami** [comment]
Hi @joonro 
I fixed this problem. Will you try latest commit?
I think the commit would not break the current behavior.

**Comment by joonro** [comment]
I just tried this and it seems to be working well - thank you so much for the quick fix!

**Comment by kiwanami** [comment]
Thank you for your confirmation!
