### ISSUE TITLE
Make the first day of week configurable [Feature request]

### ISSUE THREAD

**Issue by thblt** [kiwanami/emacs-calfw#93]
Calfw's week, two-week and month views have the week start on Sunday.  Most European (and others) calendars consider Monday the first day of the week, and Sunday the last.  Would it be possible to make the first week day configurable?

Thanks!

**Comment by kiwanami** [comment]
Hi @thblt
Did you try to set the customize variable 'calendar-week-start-day' ?

https://github.com/kiwanami/emacs-calfw/blob/master/readme.md#format-of-month-and-week-days

**Comment by thblt** [comment]
> Did you try to set the customize variable 'calendar-week-start-day' ?

I didn't, I naively assumed it would be a calfw setting, and restricted
my search to calfw|cfw... My apologies.

**Comment by thblt** [comment]
(and thanks a lot for taking the time to reply)
