### ISSUE TITLE
Hide event count

### ISSUE THREAD

**Issue by zzjjzzgggg** [kiwanami/emacs-calfw#94]
Is it possible to hide the event count after the day-of-month, e.g., "21 (1)" --> "21"?

I tried to find the pieces of code that this count is displayed, but failed. Could you please point out the lines?

Thanks!

**Comment by kiwanami** [comment]
Hi @zzjjzzgggg
You can not hide the count with any customize options.

The function 'cfw:render-calendar-cells-days' constructs the layout.
Will you check the local variable 'num-label' ?
