### ISSUE TITLE
Symbol's function definition is void: format-spec

### ISSUE THREAD

**Issue by amirteymuri** [kiwanami/emacs-calfw#96]
Hello,

i have put the following lines in my `init.el` file:

;; calendar frame work
    (require 'calfw)
    (require 'calfw-cal)

 But running the command `M-x cfw:open-diary-calendar` fails to open the calendar, showing the following error in the echo buffer:

`Symbol's function definition is void: format-spec`

**Comment by kiwanami** [comment]
Hi @amirteymuri 
Thank you for your report!
I checked the problem for `emacs -q` and fixed. Will you check it in your environment?

I haven't notice this problem because I hardly use `cfw:event` data type which is used by diary and org adapters.
This is related to #95. I would follow the problem.

**Comment by amirteymuri** [comment]
Hi,

how can i check it on my environment?

**Comment by kiwanami** [comment]
If you can pull the master branch of this repository, please try to check out.

A little while ago, the calfw entry in MELPA has been updated https://melpa.org/#/calfw.
So, if you use MELPA, you may update it now.

**Comment by amirteymuri** [comment]
Ok problem, solved! Refreshed Melpa repo and installed it from Melpa, looks like a charm! 
Thank you :+1:

**Comment by kiwanami** [comment]
Thank you for your checking!
