### ISSUE TITLE
Update launchpad for Xenial Xerus

### ISSUE THREAD

**Issue by devCram** [kiwanami/emacs-calfw#98]
Hello @kiwanami,

can you please provide an update for ubuntu 16.04 (Xenial Xerus) on [Launchpad](https://launchpad.net/ubuntu/+source/emacs-calfw) for the fix #96?

Greets,
devCram

**Comment by kiwanami** [comment]
Hi @devCram 
I put v1.6 tag on the current master.
I think launchpad can update the package. Should I notify to them?

**Comment by devCram** [comment]
Hi @kiwanami,
It's fine. I use MELPA package now.

Thanks!
